### ISSUE TITLE
scripts for Sokoban

### ISSUE THREAD

**Issue by zcczhang** [nathangrinsztajn/NoTurningBack#1]
Hi, I am just wondering if there is any script for training Sokoban that can reproduce the results in There Is No Turning Back:
A Self-Supervised Approach for Reversibility-Aware Reinforcement Learning? Thank you!

**Comment by nathangrinsztajn** [comment]
Hi, and thanks for your interest in our work! Unfortunately, the Sokoban scripts were large-scale experiments baked into the google infrastructure, so it's impossible to open-source this part of the paper... Everything else is available though, I hope it helps!
